# 넘파이와 함께 땅따먹기를-01 
#### 인문학적 시선으로 인공지능 파헤치기-07

<table align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/drive/1UGXxY8yXL-JyOIfEmlfaMCeRMBtQ3VUq#scrollTo=BjR91RBtuwe2"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />구글 코랩에서 실행하기</a>
  </td>
</table>

# 데이터 타입

In [2]:
# 대부분의 방식으로 변수 선언: int a = 8
a = 8 # 파이썬의 변수 선언
a = 'snowman' # 한 번 데이터를 담았던 변수에 다른 형태의 데이터를 담아도 OK.

In [3]:
import numpy as np

myList = [1, [2, 3], 'counting numbers'] # 가능
np.array([1, [2, 3], 'impossible']) # 의도치 않은 결과
# 데이터 타입이 우리가 의도한 정수형 하나, 리스트 하나, 문자열 하나가 아닌 '객체'라는 것에 주목.

array([1, list([2, 3]), 'impossible'], dtype=object)

# 넘파이 배열 만들기

In [6]:
example = np.array([1, 2, 3, 4, 5])
example

array([1, 2, 3, 4, 5])

In [5]:
zero =np.zeros(5, dtype = int)
zero

array([0, 0, 0, 0, 0])

In [7]:
one = np.ones(5, dtype = int)
one

array([1, 1, 1, 1, 1])

In [9]:
one_again = np.ones((2, 4), dtype = float)
one_again
# float형이니 소수점이 붙는다.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
full_of_eight = np.full((2, 4), 8)
full_of_eight

array([[8, 8, 8, 8],
       [8, 8, 8, 8]])

In [12]:
similar_to_range = np.arange(0, 30, 3)
similar_to_range
# 파이썬의 내장 함수인 range()와 흡사한 기능.

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [13]:
lucky_seven = np.linspace(0, 30, 7)
lucky_seven

array([ 0.,  5., 10., 15., 20., 25., 30.])

In [14]:
np.eye(3) # 단위행렬은 이렇게 생겼다.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.empty(5) # 메모리 주소에 들어 있던 아무 값이나 일단 집어넣는다.

array([1.9686421e-316, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
       0.0000000e+000])

# 넘파이 배열의 호패

In [ ]:
x1 = np.random.randint(10, size = 5)

In [ ]:
print(x1.ndim)

1


In [ ]:
print(x1.shape)

(5,)


In [ ]:
print(x1.size)

5


In [16]:
# 추가: 다른 차원이라면 어떻게 출력될까?
x2 = np.random.randint(10, size = (2, 4))
x2

array([[9, 1, 0, 6],
       [7, 5, 7, 2]])

In [17]:
print(x2.ndim)

2


In [18]:
print(x2.shape)

(2, 4)


In [19]:
print(x2.size)

8


In [20]:
x3 = np.random.randint(100, size = (4, 2, 5))
x3

array([[[83, 39, 43, 59, 23],
        [13, 70,  8, 61, 31]],

       [[57, 65, 16, 75, 61],
        [96, 58, 85,  6, 15]],

       [[32, 49, 70, 57, 69],
        [68, 89, 49, 19, 69]],

       [[66, 73, 66,  8, 85],
        [55, 31, 50, 54, 48]]])

In [21]:
print(x3.ndim)

3


In [22]:
print(x3.shape)

(4, 2, 5)


In [23]:
print(x3.size)

40
